/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    MOCKUP_MASSA_DOCE: THREE.Mesh
  }
  materials: {
    Burggeman_MassaDoce: THREE.MeshStandardMaterial
  }
}

export const Model = (props: JSX.IntrinsicElements['group']) => {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('src/assets/Caixa.gltf') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MOCKUP_MASSA_DOCE.geometry}
        material={materials.Burggeman_MassaDoce}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('src/assets/Caixa.gltf')
